# Generated by Django 4.2.14 on 2024-07-31 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.TextField(verbose_name='Название проекта пользователя')),
                ('project_text', models.TextField(verbose_name='Текст проекта пользователя')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Username пользователя')),
                ('answer', models.CharField(blank=True, null=True, verbose_name='Переменная для хранения ответа пользователя')),
                ('from_where', models.CharField(blank=True, null=True, verbose_name='Откуда пришел пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('vacancy_name', models.TextField(verbose_name='Название вакансии проекта')),
                ('vacancy_text', models.TextField(verbose_name='Текст вакансии проекта')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.projectmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.usermodel')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.usermodel'),
        ),
        migrations.CreateModel(
            name='CvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cv_name', models.TextField(verbose_name='Название резюме пользователя')),
                ('cv_text', models.TextField(verbose_name='Текст резюме пользователя')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.usermodel')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
