# Generated by Django 4.2.14 on 2024-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_viewed_job_id',
            field=models.IntegerField(default=0),
        ),
    ]
