# Generated by Django 4.2.14 on 2024-07-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmodel',
            name='cv_text',
            field=models.TextField(verbose_name='Текст резюме пользователя'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_text',
            field=models.TextField(verbose_name='Текст проекта пользователя'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='vacancy_text',
            field=models.TextField(verbose_name='Текст вакансии проекта'),
        ),
    ]
