# Generated by Django 4.2.14 on 2024-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_usermodel_last_viewed_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='chat_id',
            field=models.CharField(blank=True, null=True, verbose_name='Chat id пользователя'),
        ),
    ]
